# -*- coding: utf-8 -*-
require 'open-uri'
require 'net/http'

module Giddyup
  class Util
    def post_files(files)
      manifest_files = files.inject({}) do |acc, file|
        acc["#{File.basename(file)}"] => File.open(file).readlines.to_s
        acc
      end

      params = {
        "description": "This gist was ★automagically★ generated by giddyup™"
        "public": true,
        "files": manifest_files
      }

      url = URI.parse("http://github.com/gists")
      response = Net::HTTP.post_form(url, params)
      puts response.inspect
    end
  end
end
